### ISSUE TITLE
ImportError with HDP 2.5

### ISSUE THREAD

**Issue by goelprateek** [Symantec/ambari-elasticsearch-service#2]
Hi , 

I am trying to use this service with my HDP cluster , i downloaded this folder and moved to the desired location under scrvices . even i manage show service in add service section of ambari web ui . 

But when I try to install a service to nodes it gives following error and failed to install service 

`Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/ELASTICSEARCH/package/scripts/elastic_master.py", line 51, in <module>
    Elasticsearch().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 280, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/ELASTICSEARCH/package/scripts/elastic_master.py", line 16, in install
    import params
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.5/services/ELASTICSEARCH/package/scripts/params.py", line 6, in <module>
    from resource_management.libraries.functions.version import format_hdp_stack_version, compare_versions
ImportError: cannot import name format_hdp_stack_version` 

Please help me out.

**Comment by Seidzi** [comment]
HI from 2018 :D

`vim /var/lib/ambari-server/resources/stacks/HDP/${VERSION}/services/ELASTICSEARCH/package/scripts/params.py`

change `from resource_management.libraries.functions.version import format_hdp_stack_version, compare_versions`
on `from resource_management.libraries.functions.version import format_stack_version, compare_versions`
